### ISSUE TITLE
Describe how this compares with pagecache-management tools

### ISSUE THREAD

**Issue by nealmcb** [Feh/nocache#24]
Thanks - nice tool!

A tool similar to nocache is [pagecache-mangagement - A tool to permit the management of the pagecache usage of arbitrary applications - Google Project Hosting](https://code.google.com/p/pagecache-mangagement/)
It might help to compare and contrast the two in some documentation here, or steal some code, or connect with the authors, or whatever.

**Comment by beroal** [comment]
I guess that "pagecache-management" is going to die with Google Code, so this issue is no longer useful.

**Comment by Feh** [comment]
Yes, I guess you’re right.
