### ISSUE TITLE
nocache makes MC very slow

### ISSUE THREAD

**Issue by birdie-github** [Feh/nocache#39]
First, [MC](https://midnight-commander.org/) takes at least a few seconds to start.

Then, every directory change takes half a second.

I've no idea why it's happening.

**Comment by pavlinux** [comment]
It doesn’t work for me at all :)
```sh
$ env NOCACHE_FLUSHALL=1 NOCACHE_NR_FADVISE=2 nocache mc && cachestats -v  /usr/bin/mc;

pages in cache: 253/253 (100.0%)  [filesize=1012.0K, pagesize=4K]

cache map:
     0: |x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|
    32: |x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|
    64: |x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|
    96: |x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|
   128: |x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|
   160: |x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|
   192: |x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|
   224: |x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|x|`

`

**Comment by Feh** [comment]
In general the expectation of actively working to get rid of a file system cache would indeed be to slow an application down if it repeatedly accesses the file.

If you care about MC being fast when called under `nocache`, could you describe what the binary is doing? (E.g. summarize an `strace` of a typical slow action.)
