### ISSUE TITLE
GCC cache size flags

### ISSUE THREAD

**Issue by pavlinux** [Feh/nocache#41]
Anybody try/test this? :)

gcc --param "l1-cache-size=0" --param "l1-cache-line-size=0" --param "l2-cache-size=0"

**Comment by Feh** [comment]
No – what would I do with it, what would you expect to happen?

**Comment by pavlinux** [comment]
minimize use cache, Cap.

**Comment by Feh** [comment]
Hm … I mean L1 and L2 caches are quite different from what `nocache` is concerned with: page caches. Please reopen the issue if you have a concrete suggestion what `nocache` should be doing differently, thanks! :)
